version: '3.7'

volumes:
  postgres_data:
      driver: local

services:
  website:
    build: .
    ports:
      - "8080:8080"
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      volumes:
        - ./imports:/opt/jboss/keycloak/imports
      command: 
        - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/keycloak-export-manual.json"
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: keycloak
        KEYCLOAK_PASSWORD: keycloak
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8081:8080
      depends_on:
        - postgres

